apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: game-2048  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 15Gi

